### ISSUE TITLE
RuntimeError in numpy while using larq compute engine interpreter

### ISSUE THREAD

**Issue by Chidhambararajan** [larq/compute-engine#581]
I am running ubuntu20.04 with python3.8.5 and the following pip packages
- tensorflow==2.4.0
- larq==0.10.2
- larq-compute-engine==0.4.3
- larq-zoo==2.0.3
- numpy==1.19.4

All the abve packages where downloaded and installed from wheels automatically by pip  

# CODE:
```
import numpy as np
import larq_zoo as lqz

model = lqz.sota.QuickNet()

t = [np.random.rand(1,224,224,3),]

lce_model = lce.convert_keras_model(model)

interpreter = lce.tflite.python.interpreter.Interpreter(lce_model)
#interpreter = lce.testing.Interpreter(lce_model)
print(interpreter.predict(t))

```
# OUTPUT :
```
2020-12-29 12:12:11.728922: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "lceTests.py", line 13, in <module>
    print(interpreter.predict(t))
  File "/media/captain-america/7c8239eb-ca13-409c-8761-c865a3119962/Programming/binarizedSSD_Keras/venv3.7/lib/python3.8/site-packages/larq_compute_engine/tflite/python/interpreter.py", line 96, in predict
    outputs = [np.concatenate(batches) for batches in zip(*prediction_iter)]
  File "/media/captain-america/7c8239eb-ca13-409c-8761-c865a3119962/Programming/binarizedSSD_Keras/venv3.7/lib/python3.8/site-packages/larq_compute_engine/tflite/python/interpreter.py", line 95, in <genexpr>
    prediction_iter = (self.interpreter.predict(inputs) for inputs in data_iterator)
RuntimeError: NumPy type info missing for Pc

```

**Comment by Chidhambararajan** [comment]
Just to be sure I tried the same in python3.6 too. Same Error
Looks like the error is happening in the self.interpreter.predict(inputs)

**Comment by Chidhambararajan** [comment]
Just now figured it out, looks like I need to add the .astype(np.float32) to the inputs
And it works
